port: 8081
mode: debug


mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "db1"
  max_idle_conns: 20
  max_open_conns: 10

logger:
  filename: "web-app.log"
  maxsize: 20
  maxbackups: 20
  maxage: 20
  lever: "Debug"